language: node_js
node_js: '14.18.1'
cache: npm

before_script:
  - cp .env .env.local
  - sed -i 's/^VUE_APP_API_URL.*$/VUE_APP_API_URL=$VUE_APP_API_URL/' .env.local
  - sed -i 's/^BASE_URL.*$/BASE_URL=$BASE_URL/' .env.local

script:
  - npm run build
